
import type { LiveSession, LiveUser, LiveComment } from './types';

export const liveSessions: LiveSession[] = [
    {
        id: "1",
        user: { name: "Renata", avatarUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993252275-fb2ee6a1a54190c6a38eb9de11083e6c.jpg?alt=media&token=5b9c400c-ca6c-4912-a4fb-d9118c6812ee" },
        title: "Noite quente por aqui...",
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993252275-fb2ee6a1a54190c6a38eb9de11083e6c.jpg?alt=media&token=5b9c400c-ca6c-4912-a4fb-d9118c6812ee",
        videoUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993298635-Mulher_Mel_o_OF_Live_5.mp4?alt=media&token=59605958-810f-4f76-bf01-7e9a7a41e13f",
        initialViewers: "1.2k",
        chatId: "locked-3"
    },
    {
        id: "3",
        user: { name: "Vanessa", avatarUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993224509-4a67e130ab33672528eba4ce4e0df5ec.jpg?alt=media&token=0e37a2da-2a35-46ff-9cc6-7dc0fe32718a" },
        title: "Vem conversar comigo",
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993224509-4a67e130ab33672528eba4ce4e0df5ec.jpg?alt=media&token=0e37a2da-2a35-46ff-9cc6-7dc0fe32718a",
        videoUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993314196-video_969346.4982213019.mp4?alt=media&token=075b979d-21a0-49d0-90bf-35b80c581428",
        initialViewers: "950",
        chatId: "locked-4"
    },
    {
        id: "2",
        user: { name: "Luiza", avatarUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" },
        title: "Relaxando na piscina",
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d",
        videoUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993280520-video4940731004936520093.mp4?alt=media&token=83b35658-a908-4bbc-ba29-24b97b251c21",
        initialViewers: "890",
        isLocked: true,
        chatId: "locked-2"
    },
    {
        id: "4",
        user: { name: "Amanda", avatarUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993250429-a985ebd702ac65d54a6caa0f53701459.jpg?alt=media&token=228abe0d-d6fe-465a-97e4-925fbec50ad1" },
        title: "Pronta pra você",
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993250429-a985ebd702ac65d54a6caa0f53701459.jpg?alt=media&token=228abe0d-d6fe-465a-97e4-925fbec50ad1",
        videoUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993327051-video4958909342347690413.mp4?alt=media&token=b6cd1842-5c84-4c94-bd6b-2c3d6cade485",
        initialViewers: "612",
        isLocked: true,
        chatId: "locked-1"
    },
    {
        id: "fake-1",
        user: { name: "Julia", avatarUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993223143-68b2a56fb97bb6bd054d7d7450a54226.jpg?alt=media&token=7cd63cc5-eced-4cd3-913e-c6bb72349722" },
        title: "Vem me ver...",
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993223143-68b2a56fb97bb6bd054d7d7450a54226.jpg?alt=media&token=7cd63cc5-eced-4cd3-913e-c6bb72349722",
        videoUrl: "",
        initialViewers: "1.1k",
        isLocked: true
    },
    {
        id: "fake-2",
        user: { name: "Camila", avatarUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993247540-3d5cfd6b72be120870af17f7c9bb388d.jpg?alt=media&token=d704b15b-6d29-4156-972d-d0cd17d52b54" },
        title: "Sozinha em casa",
        imageUrl: "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993247540-3d5cfd6b72be120870af17f7c9bb388d.jpg?alt=media&token=d704b15b-6d29-4156-972d-d0cd17d52b54",
        videoUrl: "",
        initialViewers: "768",
        isLocked: true
    }
];

export const liveUsers: LiveUser[] = [
    { name: "Carlos", avatarUrl: "https://randomuser.me/api/portraits/men/1.jpg" },
    { name: "João", avatarUrl: "https://randomuser.me/api/portraits/men/2.jpg" },
    { name: "Pedro", avatarUrl: "https://randomuser.me/api/portraits/men/3.jpg" },
    { name: "Lucas", avatarUrl: "https://randomuser.me/api/portraits/men/4.jpg" },
    { name: "Marcos", avatarUrl: "https://randomuser.me/api/portraits/men/5.jpg" },
    { name: "Fernando", avatarUrl: "https://randomuser.me/api/portraits/men/6.jpg" },
    { name: "Ricardo", avatarUrl: "https://randomuser.me/api/portraits/men/7.jpg" },
    { name: "André", avatarUrl: "https://randomuser.me/api/portraits/men/8.jpg" },
    { name: "Felipe", avatarUrl: "https://randomuser.me/api/portraits/men/9.jpg" },
    { name: "Bruno", avatarUrl: "https://randomuser.me/api/portraits/men/10.jpg" },
    { name: "Rafael", avatarUrl: "https://randomuser.me/api/portraits/men/11.jpg" },
    { name: "Daniel", avatarUrl: "https://randomuser.me/api/portraits/men/12.jpg" },
    { name: "Gustavo", avatarUrl: "https://randomuser.me/api/portraits/men/13.jpg" },
    { name: "Marcelo", avatarUrl: "https://randomuser.me/api/portraits/men/14.jpg" },
    { name: "Rodrigo", avatarUrl: "https://randomuser.me/api/portraits/men/15.jpg" },
    { name: "Diego", avatarUrl: "https://randomuser.me/api/portraits/men/16.jpg" },
    { name: "Thiago", avatarUrl: "https://randomuser.me/api/portraits/men/17.jpg" },
    { name: "Vinicius", avatarUrl: "https://randomuser.me/api/portraits/men/18.jpg" },
    { name: "Alexandre", avatarUrl: "https://randomuser.me/api/portraits/men/19.jpg" },
    { name: "Leandro", avatarUrl: "https://randomuser.me/api/portraits/men/20.jpg" },
    { name: "Jorge", avatarUrl: "https://randomuser.me/api/portraits/men/21.jpg" },
    { name: "Eduardo", avatarUrl: "https://randomuser.me/api/portraits/men/22.jpg" },
    { name: "Roberto", avatarUrl: "https://randomuser.me/api/portraits/men/23.jpg" },
    { name: "Fábio", avatarUrl: "https://randomuser.me/api/portraits/men/24.jpg" },
    { name: "Márcio", avatarUrl: "https://randomuser.me/api/portraits/men/25.jpg" },
    { name: "Rogério", avatarUrl: "https://randomuser.me/api/portraits/men/26.jpg" },
    { name: "Sérgio", avatarUrl: "https://randomuser.me/api/portraits/men/27.jpg" },
    { name: "Renato", avatarUrl: "https://randomuser.me/api/portraits/men/28.jpg" },
    { name: "Júlio", avatarUrl: "https://randomuser.me/api/portraits/men/29.jpg" },
    { name: "Antônio", avatarUrl: "https://randomuser.me/api/portraits/men/30.jpg" },
    { name: "Leonardo", avatarUrl: "https://randomuser.me/api/portraits/men/31.jpg" },
    { name: "Francisco", avatarUrl: "https://randomuser.me/api/portraits/men/32.jpg" },
    { name: "Jonas", avatarUrl: "https://randomuser.me/api/portraits/men/33.jpg" },
    { name: "Paulo", avatarUrl: "https://randomuser.me/api/portraits/men/34.jpg" },
    { name: "Cláudio", avatarUrl: "https://randomuser.me/api/portraits/men/35.jpg" },
    { name: "Maurício", avatarUrl: "https://randomuser.me/api/portraits/men/36.jpg" },
    { name: "Gilberto", avatarUrl: "https://randomuser.me/api/portraits/men/37.jpg" },
    { name: "Valter", avatarUrl: "https://randomuser.me/api/portraits/men/38.jpg" },
    { name: "Sandro", avatarUrl: "https://randomuser.me/api/portraits/men/39.jpg" },
    { name: "Igor", avatarUrl: "https://randomuser.me/api/portraits/men/40.jpg" },
    { name: "Nelson", avatarUrl: "https://randomuser.me/api/portraits/men/41.jpg" },
    { name: "Heitor", avatarUrl: "https://randomuser.me/api/portraits/men/42.jpg" },
    { name: "Ivan", avatarUrl: "https://randomuser.me/api/portraits/men/43.jpg" },
    { name: "Vitor", avatarUrl: "https://randomuser.me/api/portraits/men/44.jpg" },
    { name: "César", avatarUrl: "https://randomuser.me/api/portraits/men/45.jpg" },
    { name: "Elias", avatarUrl: "https://randomuser.me/api/portraits/men/46.jpg" },
    { name: "Otávio", avatarUrl: "https://randomuser.me/api/portraits/men/47.jpg" },
    { name: "Davi", avatarUrl: "https://randomuser.me/api/portraits/men/48.jpg" },
    { name: "Samuel", avatarUrl: "https://randomuser.me/api/portraits/men/49.jpg" },
    { name: "Guilherme", avatarUrl: "https://randomuser.me/api/portraits/men/50.jpg" },
];

export const liveCommentsPool: string[] = [
    "Linda demais! 😍",
    "Uau, que mulher!",
    "Você é incrível!",
    "Maravilhosa!",
    "Rainha! 👑",
    "Que sorriso lindo!",
    "Estou apaixonado",
    "Casa comigo? 💍",
    "Perfeita!",
    "Deusa!",
    "A mais gata de todas",
    "Que energia boa!",
    "Adoro seu jeito",
    "Me nota!",
    "Você alegrou minha noite",
    "Que gata 🔥",
    "Manda um beijo pra mim?",
    "Show!",
    "Essa live tá demais!",
    "Você é muito simpática",
    "Que espetáculo!",
    "Essa mulher é um monumento",
    "Sem condições pra tanta beleza",
    "Que corpo é esse?",
    "Toda natural, bonita pra caramba",
    "Fico hipnotizado com você",
    "Vim pela notificação e não me arrependo",
    "A live travou aqui ou foi sua beleza?",
    "Onde eu mando o currículo?",
    "Como faz pra te encontrar?",
    "Abusadamente linda",
    "Que mulherão da p****!",
    "Gata e gente boa, pacote completo",
    "A concorrência chora",
    "Mais linda a cada dia",
    "Essa live é meu vício",
    "Vou sonhar com você hoje",
    "Sua voz me acalma",
    "Você tem um brilho diferente",
    "Que olhar... me perdi",
    "Já virei fã número 1",
    "Isso que é mulher de verdade",
    "Tem como ser mais perfeita?",
    "Meu coração até acelerou aqui",
    "Tô boquiaberto",
    "Que presença!",
    "É muita beleza pra uma pessoa só",
    "A live perfeita não exis...",
    "Cada dia mais gata",
    "Sua risada é a melhor",
    "Top demais",
    "Queria estar aí com você",
    "Essa roupa ficou incrível em você",
    "Você é uma obra de arte",
    "Como lidar com tanta perfeição?",
    "Não canso de te assistir",
    "Minha noite ficou melhor agora",
    "Você é um sonho",
    "Que mulher espetacular",
    "O tempo para quando você aparece",
    "Você tem um jeito único",
    "Dona de toda a beleza do mundo",
    "Não tem pra ninguém!",
    "A mais braba!",
    "Que isso, Brasil!",
    "Sem palavras pra você",
    "Manda salve!",
    "Que produção!",
    "A maquiagem tá impecável",
    "Sempre arrasando",
    "Diva!",
    "Meu dia tava ruim até agora",
    "Obrigado por existir",
    "Você transmite uma paz...",
    "Que mulher interessante",
    "Poderosa!",
    "Essa música de fundo é ótima",
    "Qual seu segredo pra tanta beleza?",
    "Sou seu fã",
    "A live de hoje tá especial",
    "Continue sempre assim",
    "Você é luz!",
    "Parabéns pelo seu trabalho",
    "Admiro muito você",
    "A melhor de todas",
    "Você merece todo o sucesso",
    "Incrível como sempre",
    "Que carisma!",
    "Não perco uma live sua",
    "Sempre entregando tudo",
    "Fenomenal!",
    "A dona da plataforma",
    "Amo seu conteúdo",
    "Você é muito autêntica",
    "Inspiração!",
    "É sobre isso!",
    "Que vibe boa",
    "Você é contagiante",
    "Já dei meu like!",
    "Compartilhando a live agora"
];

export const giftMessagesPool = [
    "Você é demais",
    "Um presentinho pra minha deusa",
    "Toma um mimo, linda",
    "Só pra te ver sorrir",
    "Continue com esse trabalho incrível",
    "Pra minha deusa",
    "Isso é pra você, gata",
    "Um mimo",
    "Sou seu fã número 1",
    "Toma, rainha",
    "Que mulher!",
    "Você merece",
    "A mais braba",
    "Para a melhor streamer de todas",
    "Um agrado para a mais gata",
    "Espero que ajude",
    "Toma esse PIX, maravilhosa",
    "Aceita esse presente?",
    "Você é uma inspiração",
    "Para você, com carinho",
    "Um pequeno agrado",
    "Merece o mundo!",
    "Pra dar um up na live",
    "Você faz meu dia melhor",
    "Continue brilhando",
    "Um cafézinho pra você",
    "Minha singela contribuição",
    "Sou seu maior fã!",
    "Tamo junto!",
    "Isso é por todo seu esforço",
    "Reconhecimento pelo seu talento",
    "Apoio ao seu trabalho",
    "Pra você continuar com esse conteúdo top",
    "Você é sensacional",
    "Espero que goste",
    "Um mimo do seu admirador",
    "Pra mostrar meu apoio",
    "Você é luz",
    "O mínimo que posso fazer",
    "Com todo meu carinho"
];

export const liveGifts: { text: string, amount: number }[] = [
    { text: "enviou uma Rosa", amount: 1 },
    { text: "enviou um Diamante 💎", amount: 50 },
    { text: "enviou um Coração ❤️", amount: 5 },
    { text: "enviou um Carro Esportivo 🏎️", amount: 500 },
    { text: "enviou um Foguete 🚀", amount: 1000 },
];
