
import type { TipCard } from '@/lib/types';

export const allTips: TipCard[] = [
  // Perfis de Mulheres
  { 
    id: 'match-1', 
    name: 'Melissa', 
    age: 33, 
    bio: 'Modelo e influenciadora. Adoro moda, fotografia e viagens. Buscando alguém que compartilhe minha paixão pela vida e aventuras.', 
    imageUrl: 'https://i.postimg.cc/9F0M2jM1/melissa.webp', 
    dataAiHint: 'woman smiling', 
    type: 'profile',
    distance: 'a 4km de você',
    tags: ['Moda', 'Fotografia', 'Fitness'],
  },
  { 
    id: 'match-2', 
    name: 'Jéssica', 
    age: 29, 
    bio: 'Empresária e amante de um bom vinho. Gosto de conversas profundas e noites tranquilas em casa.', 
    imageUrl: 'https://i.postimg.cc/t4G29gSw/jessica.webp',
    dataAiHint: 'woman serious', 
    type: 'profile',
    distance: 'a 12km de você',
    tags: ['Vinhos', 'Negócios', 'Cultura'],
  },
  { 
    id: 'match-3', 
    name: 'Amanda', 
    age: 35, 
    bio: 'Advogada durante o dia, exploradora de novos restaurantes à noite. Me ganha com inteligência e bom humor.', 
    imageUrl: 'https://i.postimg.cc/cCZ2L36d/profile-amanda.webp', 
    dataAiHint: 'woman looking away', 
    type: 'profile',
    distance: 'a 8km de você',
    tags: ['Gastronomia', 'Direito', 'Viagens'],
  },
  { 
    id: 'match-4', 
    name: 'Renata', 
    age: 41, 
    bio: 'Médica, apaixonada por arte e longas caminhadas no parque. Procuro uma conexão real e sem jogos.', 
    imageUrl: 'https://madames.online/wp-content/uploads/2026/01/O6sUjXlb3.jpeg',
    dataAiHint: 'woman nature', 
    type: 'profile',
    distance: 'a 2km de você',
    tags: ['Saúde', 'Arte', 'Natureza'],
  },
  { 
    id: 'match-5', 
    name: 'Luiza', 
    age: 38, 
    bio: 'Arquiteta com alma de artista. Curto exposições, shows de jazz e um bom café. Acredito que a vida é curta demais para não ser intensa.', 
    imageUrl: 'https://i.postimg.cc/xTCDJW9H/profile-luiza.webp',
    dataAiHint: 'woman city', 
    type: 'profile',
    distance: 'a 5km de você',
    tags: ['Arquitetura', 'Jazz', 'Café'],
  },
  {
    id: 'match-6',
    name: 'Camila',
    age: 28,
    bio: 'Apaixonada por música e cinema. Buscando alguém para compartilhar momentos. Amo natureza, animais e boas conversas.',
    imageUrl: 'https://i.postimg.cc/6pB6Yj7V/camila.webp',
    dataAiHint: 'woman bed',
    type: 'profile',
    distance: 'a 1km de você',
    tags: ['Música', 'Cinema', 'Arte'],
  },
  {
    id: 'match-7',
    name: 'Sofia',
    age: 30,
    bio: 'Designer e criadora de conteúdo. A vida é uma tela em branco, e eu adoro colorir. Vamos pintar uma história juntos?',
    imageUrl: 'https://i.postimg.cc/Z5HdtYtN/sofia.webp',
    dataAiHint: 'woman modern',
    type: 'profile',
    distance: 'a 6km de você',
    tags: ['Design', 'Criatividade', 'Viagens'],
  },
  {
    id: 'match-8',
    name: 'Mariana',
    age: 34,
    bio: 'Personal trainer. Corpo em movimento, mente sã. Se você curte uma vida ativa e um bom açaí, já temos algo em comum.',
    imageUrl: 'https://i.postimg.cc/9QG7pM27/mariana.webp',
    dataAiHint: 'woman fitness',
    type: 'profile',
    distance: 'a 3km de você',
    tags: ['Fitness', 'Praia', 'Vida Saudável'],
  },
  {
    id: 'match-9',
    name: 'Isabela',
    age: 27,
    bio: 'Psicóloga. Entendo de mentes, mas quero entender da sua. Curto conversas que fluem e um bom livro no fim do dia.',
    imageUrl: 'https://i.postimg.cc/PqYv6JFY/isabela.webp',
    dataAiHint: 'woman reading',
    type: 'profile',
    distance: 'a 9km de você',
    tags: ['Psicologia', 'Livros', 'Café'],
  },
  {
    id: 'match-10',
    name: 'Carolina',
    age: 39,
    bio: 'Chef de cozinha. Acredito que o amor passa pelo estômago. Qual seu prato favorito? Me convença a cozinhar para você.',
    imageUrl: 'https://i.postimg.cc/mD3mGGm3/carolina.webp',
    dataAiHint: 'woman cooking',
    type: 'profile',
    distance: 'a 7km de você',
    tags: ['Culinária', 'Vinhos', 'Jantar'],
  },
   {
    id: 'match-11',
    name: 'Gabriela',
    age: 32,
    bio: 'Fotógrafa. Capturo momentos, mas o melhor momento é o agora. Gosto de explorar a cidade e encontrar beleza no caos.',
    imageUrl: 'https://i.postimg.cc/7PM3TGB9/gabriela.webp',
    dataAiHint: 'woman photographer',
    type: 'profile',
    distance: 'a 11km de você',
    tags: ['Fotografia', 'Urbano', 'Arte'],
  },
  {
    id: 'match-12',
    name: 'Laura',
    age: 42,
    bio: 'Advogada corporativa. Trabalho muito, mas me divirto na mesma intensidade. Adoro um bom desafio, no trabalho e na vida.',
    imageUrl: 'https://i.postimg.cc/d1hDjyqJ/laura.webp',
    dataAiHint: 'woman professional',
    type: 'profile',
    distance: 'a 15km de você',
    tags: ['Direito', 'Viagens de Negócios', 'Luxo'],
  },
  {
    id: 'match-13',
    name: 'Beatriz',
    age: 36,
    bio: 'Veterinária. Amo animais mais do que gente (brincadeira... ou não). Se você tem um pet, já ganhou pontos.',
    imageUrl: 'https://i.postimg.cc/Y0BBgR6P/beatriz.webp',
    dataAiHint: 'woman with dog',
    type: 'profile',
    distance: 'a 5km de você',
    tags: ['Animais', 'Natureza', 'Trilhas'],
  },
  {
    id: 'match-14',
    name: 'Bruna',
    age: 26,
    bio: 'Jornalista. Conto histórias para viver, mas estou em busca de uma boa história para chamar de nossa.',
    imageUrl: 'https://i.postimg.cc/W3sL2bWc/bruna.webp',
    dataAiHint: 'woman writing',
    type: 'profile',
    distance: 'a 10km de você',
    tags: ['Jornalismo', 'Cultura Pop', 'Cinema'],
  },
  {
    id: 'match-15',
    name: 'Clara',
    age: 37,
    bio: 'Piloto de avião. Vivo nas nuvens, mas procuro alguém para me trazer de volta à terra (ou voar comigo).',
    imageUrl: 'https://i.postimg.cc/j5GgC08D/clara.webp',
    dataAiHint: 'woman pilot',
    type: 'profile',
    distance: 'a 25km de você',
    tags: ['Aviação', 'Aventura', 'Mundo'],
  },
   {
    id: 'match-16',
    name: 'Helena',
    age: 45,
    bio: 'Dona de uma galeria de arte. A beleza está nos olhos de quem vê, e eu estou de olho em você. Me surpreenda.',
    imageUrl: 'https://i.postimg.cc/yd3ySgZT/helena.webp',
    dataAiHint: 'woman elegant',
    type: 'profile',
    distance: 'a 8km de você',
    tags: ['Arte', 'Sofisticação', 'Cultura'],
  },
  {
    id: 'match-17',
    name: 'Valentina',
    age: 31,
    bio: 'Musicista. Toco violino e meu coração bate no ritmo de uma boa sinfonia. Qual é a trilha sonora da sua vida?',
    imageUrl: 'https://i.postimg.cc/xT3x0sT6/valentina.webp',
    dataAiHint: 'woman musician',
    type: 'profile',
    distance: 'a 14km de você',
    tags: ['Música Clássica', 'Concertos', 'Romance'],
  },
  {
    id: 'match-18',
    name: 'Alice',
    age: 29,
    bio: 'Cientista de dados. Transformo números em histórias. Mas e a nossa história, quando começa?',
    imageUrl: 'https://i.postimg.cc/k47GvBf7/alice.webp',
    dataAiHint: 'woman tech',
    type: 'profile',
    distance: 'a 18km de você',
    tags: ['Tecnologia', 'Inteligência', 'Futuro'],
  },
  {
    id: 'match-19',
    name: 'Manuela',
    age: 40,
    bio: 'CEO. Lidero uma empresa, mas na vida pessoal gosto de ser liderada por uma boa conversa e um sorriso sincero.',
    imageUrl: 'https://i.postimg.cc/bN1dKjH4/manuela.webp',
    dataAiHint: 'woman ceo',
    type: 'profile',
    distance: 'a 12km de você',
    tags: ['Negócios', 'Poder', 'Desafios'],
  },
  {
    id: 'match-20',
    name: 'Yasmin',
    age: 33,
    bio: 'Youtuber de viagens. O mundo é meu escritório. Topa ser meu companheiro de aventuras e gravar nosso próprio "felizes para sempre"?',
    imageUrl: 'https://i.postimg.cc/pT3Y3bK8/yasmin.webp',
    dataAiHint: 'woman travel',
    type: 'profile',
    distance: 'a 22km de você',
    tags: ['Viagens', 'Aventura', 'Youtube'],
  },
  { 
    id: 'match-21', 
    name: 'Luciana', 
    age: 54, 
    bio: 'Empresária bem-sucedida, mãe de três filhos adultos. Adoro cozinhar, viajar e apreciar um bom vinho....', 
    imageUrl: 'https://i.postimg.cc/Dyd1gCF1/luciana-profile.webp', 
    dataAiHint: 'woman smiling', 
    type: 'profile',
    distance: 'a 1km de você',
    tags: ['Gastronomia', 'Vinhos', 'Viagens'],
  },
  
  // Conteúdo Educacional
  { 
    id: 'content-1', 
    name: '1. Perfil Blindado', 
    age: 99, 
    bio: 'Como virar desejo em segundos. Deslize para a direita para salvar e aprender.', 
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993396272-profile-patricia.webp?alt=media&token=d2845190-8ad7-4b6c-a39f-34f7b682714e', 
    dataAiHint: 'man confident', 
    type: 'article', 
    href: '/capitulo-1' 
  },
  { 
    id: 'content-2', 
    name: '2. Primeira Mensagem Ninja', 
    age: 99,
    bio: 'A arte de nunca mais levar vácuo. Salve esta dica e domine a conversa.', 
    imageUrl: 'https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993395076-profile-pool.webp?alt=media&token=a1184e54-1d66-4c16-ae0c-0b198718e731', 
    dataAiHint: 'man texting', 
    type: 'article', 
    href: '/capitulo-2' 
  },
   { 
    id: 'content-3', 
    name: 'Analista de Bio com IA', 
    age: 99,
    bio: 'Deixe nossa IA analisar e otimizar sua bio para gerar mais matches.', 
    imageUrl: 'https://i.postimg.cc/yNn4YyG7/ai-bio.webp',
    dataAiHint: 'robot writing', 
    type: 'photo-analyzer', 
    href: '/analise-bio' 
  },
];
