
import type { VideoPost } from './types';

export const allVideos: VideoPost[] = [
    {
        "id": "video-1",
        "user": {
            "name": "Brenda",
            "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec"
        },
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec",
        "videoUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993227058-Babe_Big_Tits_Boobs_Brunette_Cute_Homemade_Latina_Petite_Solo_Tits_Porn_Gif_by_sofiaaamoreno___RedGIFs.mp4?alt=media&token=004b7497-48fe-4deb-8c25-1084e06c70f2",
        "caption": "Um presentinho pra você... gostou? 🎁 #fyp",
        "likes": 1247,
        "comments": [
            { "id": "c1-1", "user": { "name": "Carlos", "avatarUrl": "https://randomuser.me/api/portraits/men/1.jpg" }, "text": "Gostei? Eu amei! Melhor presente do dia! 🔥", "date": "5h", "likes": 93, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Que bom que gostou, amor! Fico feliz. ❤️", "date": "4h", "likes": 55 }] },
            { "id": "c1-2", "user": { "name": "João", "avatarUrl": "https://randomuser.me/api/portraits/men/2.jpg" }, "text": "Simplesmente perfeita, um espetáculo de mulher!", "date": "5h", "likes": 89, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Obrigada, meu bem! Você é um fofo. ❤️", "date": "4h", "likes": 51 }] },
            { "id": "c1-3", "user": { "name": "Pedro", "avatarUrl": "https://randomuser.me/api/portraits/men/3.jpg" }, "text": "Que presentão! Assim você me quebra!", "date": "5h", "likes": 86, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Hahaha adoro quebrar vocês 😈", "date": "4h", "likes": 48 }] },
            { "id": "c1-4", "user": { "name": "Lucas", "avatarUrl": "https://randomuser.me/api/portraits/men/4.jpg" }, "text": "Você é uma deusa, não tem como.", "date": "5h", "likes": 82, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Assim eu fico sem graça, lindo. 🥰", "date": "4h", "likes": 45 }] },
            { "id": "c1-5", "user": { "name": "Marcos", "avatarUrl": "https://randomuser.me/api/portraits/men/5.jpg" }, "text": "Se esse é o presentinho, imagina o principal.", "date": "5h", "likes": 79, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Hahaha o principal eu guardo pra quem merece. 😉", "date": "4h", "likes": 43 }] },
            { "id": "c1-6", "user": { "name": "Fernando", "avatarUrl": "https://randomuser.me/api/portraits/men/6.jpg" }, "text": "Como pode ser tão gata?", "date": "4h", "likes": 77, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "É de família, amor! hahaha", "date": "4h", "likes": 41 }] },
            { "id": "c1-7", "user": { "name": "Ricardo", "avatarUrl": "https://randomuser.me/api/portraits/men/7.jpg" }, "text": "Deusa!", "date": "4h", "likes": 75, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Obrigada, meu lindo! 😘", "date": "3h", "likes": 39 }] },
            { "id": "c1-8", "user": { "name": "André", "avatarUrl": "https://randomuser.me/api/portraits/men/8.jpg" }, "text": "Aceito esse presente todo dia.", "date": "4h", "likes": 72, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Posso te dar um todo dia, se você pedir com jeitinho. 😉", "date": "4h", "likes": 38 }] },
            { "id": "c1-9", "user": { "name": "Felipe", "avatarUrl": "https://randomuser.me/api/portraits/men/9.jpg" }, "text": "Você alegrou minha noite", "date": "3h", "likes": 69, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Fico feliz, anjo. Espero alegrar muitas outras noites suas. 🥰", "date": "3h", "likes": 36 }] },
            { "id": "c1-10", "user": { "name": "Bruno", "avatarUrl": "https://randomuser.me/api/portraits/men/10.jpg" }, "text": "Manda um beijo pra mim?", "date": "3h", "likes": 66, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Um beijo bem gostoso pra você, meu amor! 💋", "date": "3h", "likes": 34 }] },
            { "id": "c1-11", "user": { "name": "Rafael", "avatarUrl": "https://randomuser.me/api/portraits/men/11.jpg" }, "text": "Essa mulher é um monumento", "date": "3h", "likes": 64, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Obrigada, lindo! Quem sabe um dia você não explora de perto... 😏", "date": "3h", "likes": 32 }] },
            { "id": "c1-12", "user": { "name": "Daniel", "avatarUrl": "https://randomuser.me/api/portraits/men/12.jpg" }, "text": "Obrigado pelo presente, meu dia melhorou 100%.", "date": "2h", "likes": 61, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Que bom, fofo! Fico feliz em saber disso. ❤️", "date": "2h", "likes": 30 }] },
            { "id": "c1-13", "user": { "name": "Gustavo", "avatarUrl": "https://randomuser.me/api/portraits/men/13.jpg" }, "text": "Toda natural, bonita pra caramba", "date": "2h", "likes": 59, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Obrigada, meu bem! Tento me cuidar.", "date": "2h", "likes": 29 }] },
            { "id": "c1-14", "user": { "name": "Marcelo", "avatarUrl": "https://randomuser.me/api/portraits/men/14.jpg" }, "text": "Vim pela notificação e não me arrependo", "date": "2h", "likes": 57, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Fico feliz que veio! Espero que continue por aqui.", "date": "2h", "likes": 27 }] },
            { "id": "c1-15", "user": { "name": "Rodrigo", "avatarUrl": "https://randomuser.me/api/portraits/men/15.jpg" }, "text": "Onde eu mando o currículo pra ser seu?", "date": "2h", "likes": 55, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Hahaha, fofo! Quem sabe um dia... 😉", "date": "2h", "likes": 26 }] },
            { "id": "c1-16", "user": { "name": "Diego", "avatarUrl": "https://randomuser.me/api/portraits/men/16.jpg" }, "text": "Que mulherão da p****", "date": "2h", "likes": 53, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Sou mesmo, bebê! 😉", "date": "2h", "likes": 25 }] },
            { "id": "c1-17", "user": { "name": "Thiago", "avatarUrl": "https://randomuser.me/api/portraits/men/17.jpg" }, "text": "A concorrência chora", "date": "1h", "likes": 51, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Deixo mesmo! hahaha 😈", "date": "1h", "likes": 23 }] },
            { "id": "c1-18", "user": { "name": "Vinicius", "avatarUrl": "https://randomuser.me/api/portraits/men/18.jpg" }, "text": "Gostei do presente. Tem mais?", "date": "1h", "likes": 48, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Tem muito mais... mas os melhores eu guardo pra depois. 😉", "date": "1h", "likes": 22 }] },
            { "id": "c1-19", "user": { "name": "Alexandre", "avatarUrl": "https://randomuser.me/api/portraits/men/19.jpg" }, "text": "Isso que é um presentão de verdade!", "date": "58m", "likes": 46, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Eu sei ser generosa com quem merece, meu bem.", "date": "57m", "likes": 21 }] },
            { "id": "c1-20", "user": { "name": "Leandro", "avatarUrl": "https://randomuser.me/api/portraits/men/20.jpg" }, "text": "Que olhar... me perdi", "date": "55m", "likes": 43, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Se acha então, bebê. Gosto de homens que se perdem em mim.", "date": "54m", "likes": 20 }] },
            { "id": "c1-21", "user": { "name": "Daniel", "avatarUrl": "https://randomuser.me/api/portraits/men/21.jpg" }, "text": "Isso que é mulher de verdade", "date": "50m", "likes": 40, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "Pode ter certeza, meu amor!", "date": "49m", "likes": 19 }] },
            { "id": "c1-22", "user": { "name": "Gustavo", "avatarUrl": "https://randomuser.me/api/portraits/men/22.jpg" }, "text": "Meu coração até acelerou aqui", "date": "45m", "likes": 38, "replies": [{ "user": { "name": "Brenda", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993221831-8b05c1cd90b47adb0db20a7f93a18bc2.jpg?alt=media&token=59818897-70e0-43f5-a48c-95d30e616aec" }, "text": "O meu também, só de te imaginar. ❤️", "date": "44m", "likes": 18 }] }
        ]
    },
    {
        "id": "video-2",
        "user": {
            "name": "Carla",
            "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d"
        },
        "imageUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d",
        "videoUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993234103-Amateur_Babe_Big_Tits_Boobs_Brunette_Cute_MILF_NSFW_Tits_Porn_Gif_by_chbeauty___RedGIFs.mp4?alt=media&token=d9cc99c7-33d7-4ff4-aee2-1ad7fd232f8f",
        "caption": "Te esperando assim... vai demorar pra chegar? 🔥 #vemlogo",
        "likes": 1189,
        "comments": [
            { "id": "c2-1", "user": { "name": "Pedro", "avatarUrl": "https://randomuser.me/api/portraits/men/43.jpg" }, "text": "Tô chegando! Me passa o endereço. 😍", "date": "3h", "likes": 85, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Hahaha, que ousado! Adorei.", "date": "2h", "likes": 50 }] },
            { "id": "c2-2", "user": { "name": "Marcos", "avatarUrl": "https://randomuser.me/api/portraits/men/44.jpg" }, "text": "Uma sereia fora d'água.", "date": "3h", "likes": 81, "isPinned": true, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Adorei a cantada, fofo. ❤️", "date": "3h", "likes": 48 }] },
            { "id": "c2-3", "user": { "name": "Carlos", "avatarUrl": "https://randomuser.me/api/portraits/men/45.jpg" }, "text": "Que espetáculo!", "date": "3h", "likes": 78, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Obrigada, lindo! ❤️", "date": "2h", "likes": 45 }] },
            { "id": "c2-4", "user": { "name": "João", "avatarUrl": "https://randomuser.me/api/portraits/men/46.jpg" }, "text": "Se eu chegar aí o estrago vai ser grande...", "date": "3h", "likes": 75, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Adoro um estrago... 😏", "date": "3h", "likes": 43 }] },
            { "id": "c2-5", "user": { "name": "Lucas", "avatarUrl": "https://randomuser.me/api/portraits/men/47.jpg" }, "text": "Que corpo é esse?", "date": "3h", "likes": 72, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Gostou, né? Imagina vendo de perto... 🔥", "date": "3h", "likes": 41 }] },
            { "id": "c2-6", "user": { "name": "Fernando", "avatarUrl": "https://randomuser.me/api/portraits/men/48.jpg" }, "text": "Fico hipnotizado com você", "date": "2h", "likes": 69, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Essa é a intenção, meu bem. 😉", "date": "2h", "likes": 39 }] },
            { "id": "c2-7", "user": { "name": "Ricardo", "avatarUrl": "https://randomuser.me/api/portraits/men/49.jpg" }, "text": "Vou correndo, aonde você tá?", "date": "2h", "likes": 67, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Correndo assim vai ficar cansado, amor. Vem com calma.", "date": "1h", "likes": 37 }] },
            { "id": "c2-8", "user": { "name": "André", "avatarUrl": "https://randomuser.me/api/portraits/men/50.jpg" }, "text": "Como faz pra te encontrar?", "date": "2h", "likes": 65, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Um passo de cada vez, meu anjo. Quem sabe...", "date": "2h", "likes": 35 }] },
            { "id": "c2-9", "user": { "name": "Felipe", "avatarUrl": "https://randomuser.me/api/portraits/men/51.jpg" }, "text": "Abusadamente linda", "date": "2h", "likes": 63, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Sempre, bebê! 😉", "date": "2h", "likes": 33 }] },
            { "id": "c2-10", "user": { "name": "Bruno", "avatarUrl": "https://randomuser.me/api/portraits/men/52.jpg" }, "text": "Gata e gente boa, pacote completo", "date": "2h", "likes": 60, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "O pacote completo tem surpresas, bebê. 😘", "date": "1h", "likes": 31 }] },
            { "id": "c2-11", "user": { "name": "Rafael", "avatarUrl": "https://randomuser.me/api/portraits/men/53.jpg" }, "text": "Mais linda a cada dia", "date": "2h", "likes": 58, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Obrigada, meu amor! ❤️", "date": "2h", "likes": 29 }] },
            { "id": "c2-12", "user": { "name": "Daniel", "avatarUrl": "https://randomuser.me/api/portraits/men/54.jpg" }, "text": "Não demoro, já tô a caminho.", "date": "2h", "likes": 55, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Estou te esperando ansiosa!", "date": "2h", "likes": 27 }] },
            { "id": "c2-13", "user": { "name": "Gustavo", "avatarUrl": "https://randomuser.me/api/portraits/men/55.jpg" }, "text": "Você tem um brilho diferente", "date": "1h", "likes": 53, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Você que tem olhos bons, fofo.", "date": "1h", "likes": 25 }] },
            { "id": "c2-14", "user": { "name": "Marcelo", "avatarUrl": "https://randomuser.me/api/portraits/men/56.jpg" }, "text": "Já virei fã número 1", "date": "1h", "likes": 51, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Own, que amor! ❤️", "date": "1h", "likes": 23 }] },
            { "id": "c2-15", "user": { "name": "Rodrigo", "avatarUrl": "https://randomuser.me/api/portraits/men/57.jpg" }, "text": "Tem como ser mais perfeita?", "date": "1h", "likes": 49, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Se eu te contar meu segredo, estraga a surpresa. 😉", "date": "1h", "likes": 22 }] },
            { "id": "c2-16", "user": { "name": "Diego", "avatarUrl": "https://randomuser.me/api/portraits/men/58.jpg" }, "text": "Uau, que mulher!", "date": "50m", "likes": 47, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Gostou, foi? 😏", "date": "49m", "likes": 20 }] },
            { "id": "c2-17", "user": { "name": "Thiago", "avatarUrl": "https://randomuser.me/api/portraits/men/59.jpg" }, "text": "Linda demais! 😍", "date": "48m", "likes": 45, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Obrigada, vida! 😘", "date": "47m", "likes": 18 }] },
            { "id": "c2-18", "user": { "name": "Vinicius", "avatarUrl": "https://randomuser.me/api/portraits/men/60.jpg" }, "text": "Maravilhosa!", "date": "47m", "likes": 43, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Você que é, meu bem! ❤️", "date": "46m", "likes": 16 }] },
            { "id": "c2-19", "user": { "name": "Anônimo", "avatarUrl": "https://randomuser.me/api/portraits/men/61.jpg" }, "text": "Que paraíso!", "date": "45m", "likes": 40, "replies": [{ "user": { "name": "Carla", "avatarUrl": "https://firebasestorage.googleapis.com/v0/b/mentoros-app.firebasestorage.app/o/media-hub%2FMAbrOVJfktZcWonkiLv4OS8eDc12%2F1781993220559-06773eb71173294c6ba9c2a60a8d70c4.jpg?alt=media&token=1c6dc1d0-71de-4e2b-ac0b-4928aa2ed91d" }, "text": "Vem conhecer o paraíso de perto. 😉", "date": "44m", "likes": 15 }] }
        ]
    },
    {
        "id": "video-3",
        "user": {
            "name": "Larissa",
            "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg"
        },
        "imageUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg",
        "videoUrl": "https://madames.online/wp-content/uploads/2025/11/Ass-Big-Ass-Big-Tits-Boobs-Brunette-Cute-MILF-OnlyFans-Porn-Gif-by-lyrame-_-RedGIFs.mp4",
        "caption": "Tudo isso pode ser seu... mas só se você for bom menino. 😏",
        "likes": 1302,
        "comments": [
            { "id": "c3-1", "user": { "name": "Fernando", "avatarUrl": "https://randomuser.me/api/portraits/men/73.jpg" }, "text": "Eu sou um ótimo menino, pode confiar!", "date": "6h", "likes": 105, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Humm, será? Gosto de meninos bons... 😉", "date": "5h", "likes": 51 }] },
            { "id": "c3-2", "user": { "name": "Ricardo", "avatarUrl": "https://randomuser.me/api/portraits/men/74.jpg" }, "text": "Perfeição define. Onde compra uma dessa?", "date": "6h", "likes": 101, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Hahaha, não vende em loja, amor. Essa aqui é peça única.", "date": "6h", "likes": 49 }] },
            { "id": "c3-3", "user": { "name": "Carlos", "avatarUrl": "https://randomuser.me/api/portraits/men/75.jpg" }, "text": "Essa mulher é um monumento", "date": "6h", "likes": 98, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Um monumento que você pode visitar quando quiser... 😏", "date": "6h", "likes": 45 }] },
            { "id": "c3-4", "user": { "name": "João", "avatarUrl": "https://randomuser.me/api/portraits/men/76.jpg" }, "text": "O que eu preciso fazer pra ser seu?", "date": "6h", "likes": 95, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Para ser meu tem que ter atitude, bebê. 🔥", "date": "5h", "likes": 48 }] },
            { "id": "c3-5", "user": { "name": "Pedro", "avatarUrl": "https://randomuser.me/api/portraits/men/77.jpg" }, "text": "Sem condições pra tanta beleza", "date": "5h", "likes": 92, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Ah, meu bem... você não viu nada ainda.", "date": "5h", "likes": 44 }] },
            { "id": "c3-6", "user": { "name": "Lucas", "avatarUrl": "https://randomuser.me/api/portraits/men/78.jpg" }, "text": "Toda natural, bonita pra caramba", "date": "5h", "likes": 89, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Obrigada, lindo! ❤️", "date": "5h", "likes": 42 }] },
            { "id": "c3-7", "user": { "name": "Marcos", "avatarUrl": "https://randomuser.me/api/portraits/men/79.jpg" }, "text": "Vim pela notificação e não me arrependo", "date": "5h", "likes": 86, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Veio ao lugar certo! Continue por aqui...", "date": "5h", "likes": 41 }] },
            { "id": "c3-8", "user": { "name": "André", "avatarUrl": "https://randomuser.me/api/portraits/men/80.jpg" }, "text": "Eu sou um bom menino. O que eu ganho?", "date": "4h", "likes": 83, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Ganha minha atenção... 😏", "date": "3h", "likes": 40 }] },
            { "id": "c3-9", "user": { "name": "Felipe", "avatarUrl": "https://randomuser.me/api/portraits/men/81.jpg" }, "text": "Que mulherão da p****", "date": "4h", "likes": 80, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Com muito prazer, bebê! 😉", "date": "4h", "likes": 38 }] },
            { "id": "c3-10", "user": { "name": "Bruno", "avatarUrl": "https://randomuser.me/api/portraits/men/82.jpg" }, "text": "A concorrência chora", "date": "4h", "likes": 77, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Deixo chorando mesmo! 💅", "date": "4h", "likes": 36 }] },
            { "id": "c3-11", "user": { "name": "Rafael", "avatarUrl": "https://randomuser.me/api/portraits/men/83.jpg" }, "text": "Vou sonhar com você hoje", "date": "3h", "likes": 75, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Espero que seja um sonho bem safado... 😏", "date": "3h", "likes": 34 }] },
            { "id": "c3-12", "user": { "name": "Daniel", "avatarUrl": "https://randomuser.me/api/portraits/men/84.jpg" }, "text": "Que olhar... me perdi", "date": "3h", "likes": 72, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Se acha então, meu bem.", "date": "3h", "likes": 32 }] },
            { "id": "c3-13", "user": { "name": "Gustavo", "avatarUrl": "https://randomuser.me/api/portraits/men/85.jpg" }, "text": "Isso que é mulher de verdade", "date": "3h", "likes": 69, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Pode apostar, fofo!", "date": "3h", "likes": 30 }] },
            { "id": "c3-14", "user": { "name": "Marcelo", "avatarUrl": "https://randomuser.me/api/portraits/men/86.jpg" }, "text": "Meu coração até acelerou aqui", "date": "3h", "likes": 67, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "O meu também! Imagina pessoalmente...", "date": "3h", "likes": 29 }] },
            { "id": "c3-15", "user": { "name": "Rodrigo", "avatarUrl": "https://randomuser.me/api/portraits/men/87.jpg" }, "text": "Linda demais! 😍", "date": "2h", "likes": 65, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Obrigada, delícia!", "date": "2h", "likes": 28 }] },
            { "id": "c3-16", "user": { "name": "Diego", "avatarUrl": "https://randomuser.me/api/portraits/men/88.jpg" }, "text": "Maravilhosa!", "date": "2h", "likes": 62, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Você que é, meu bem!", "date": "2h", "likes": 27 }] },
            { "id": "c3-17", "user": { "name": "Thiago", "avatarUrl": "https://randomuser.me/api/portraits/men/89.jpg" }, "text": "Prometo que vou ser um bom menino.", "date": "2h", "likes": 60, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Adoro promessas... vamos ver se você cumpre. 😉", "date": "1h", "likes": 26 }] },
            { "id": "c3-18", "user": { "name": "Vinicius", "avatarUrl": "https://randomuser.me/api/portraits/men/90.jpg" }, "text": "Perfeita!", "date": "2h", "likes": 58, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Sou mesmo... e só quem é especial descobre o quão perfeita eu posso ser. 🔥", "date": "2h", "likes": 25 }] },
            { "id": "c3-19", "user": { "name": "Alexandre", "avatarUrl": "https://randomuser.me/api/portraits/men/91.jpg" }, "text": "A mais gata de todas", "date": "1h", "likes": 55, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Pode ter certeza disso, amor!", "date": "1h", "likes": 24 }] },
            { "id": "c3-20", "user": { "name": "Anônimo", "avatarUrl": "https://randomuser.me/api/portraits/men/92.jpg" }, "text": "Essa é a melhor!", "date": "1h", "likes": 53, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Sou mesmo! haha", "date": "1h", "likes": 23 }] },
            { "id": "c3-21", "user": { "name": "Anônimo", "avatarUrl": "https://randomuser.me/api/portraits/men/93.jpg" }, "text": "Que vídeo!", "date": "50m", "likes": 51, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Imagina os outros vídeos...", "date": "49m", "likes": 22 }] },
            { "id": "c3-22", "user": { "name": "Anônimo", "avatarUrl": "https://randomuser.me/api/portraits/men/94.jpg" }, "text": "Que tentação!", "date": "45m", "likes": 48, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Sou a tentação em pessoa, bebê.", "date": "44m", "likes": 21 }] },
            { "id": "c3-23", "user": { "name": "Anônimo", "avatarUrl": "https://randomuser.me/api/portraits/men/95.jpg" }, "text": "Uau!", "date": "40m", "likes": 45, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Gostou, né? 😏", "date": "39m", "likes": 20 }] },
            { "id": "c3-24", "user": { "name": "Anônimo", "avatarUrl": "https://randomuser.me/api/portraits/men/96.jpg" }, "text": "Dei like!", "date": "30m", "likes": 42, "replies": [{ "user": { "name": "Larissa", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/68b2a56fb97bb6bd054d7d7450a54226.jpg" }, "text": "Obrigada pelo carinho, amor!", "date": "29m", "likes": 19 }] }
        ]
    },
    {
        "id": "video-4",
        "user": {
            "name": "Yasmin",
            "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg"
        },
        "imageUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg",
        "videoUrl": "https://madames.online/wp-content/uploads/2025/11/Big-Tits-MILF-Tits-Porn-Gif-by-steph45-_-RedGIFs.mp4",
        "caption": "Só pra te deixar com vontade... 😋 #provocando",
        "likes": 1153,
        "comments": [
            { "id": "c4-1", "user": { "name": "Bruno", "avatarUrl": "https://randomuser.me/api/portraits/men/5.jpg" }, "text": "Missão cumprida, já estou com muita vontade!", "date": "8h", "likes": 90, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Fico feliz que gostou... 🔥", "date": "7h", "likes": 45 }] },
            { "id": "c4-2", "user": { "name": "Carlos", "avatarUrl": "https://randomuser.me/api/portraits/men/6.jpg" }, "text": "Que mulher! 🔥", "date": "8h", "likes": 87, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Obrigada, gato! 😉", "date": "8h", "likes": 43 }] },
            { "id": "c4-3", "user": { "name": "João", "avatarUrl": "https://randomuser.me/api/portraits/men/7.jpg" }, "text": "Simplesmente perfeita", "date": "8h", "likes": 84, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Você que é, meu lindo!", "date": "8h", "likes": 41 }] },
            { "id": "c4-4", "user": { "name": "Pedro", "avatarUrl": "https://randomuser.me/api/portraits/men/8.jpg" }, "text": "Essa provocação funcionou demais aqui.", "date": "7h", "likes": 81, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Eu sei, meu bem. 😉", "date": "6h", "likes": 39 }] },
            { "id": "c4-5", "user": { "name": "Lucas", "avatarUrl": "https://randomuser.me/api/portraits/men/9.jpg" }, "text": "Rainha! 👑", "date": "7h", "likes": 79, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Pode me chamar assim, eu deixo! haha", "date": "7h", "likes": 38 }] },
            { "id": "c4-6", "user": { "name": "Marcos", "avatarUrl": "https://randomuser.me/api/portraits/men/10.jpg" }, "text": "Que sorriso lindo!", "date": "7h", "likes": 76, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Obrigada, amor! ❤️", "date": "7h", "likes": 36 }] },
            { "id": "c4-7", "user": { "name": "Fernando", "avatarUrl": "https://randomuser.me/api/portraits/men/11.jpg" }, "text": "Casa comigo? 💍", "date": "6h", "likes": 73, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Hahaha, vamos com calma, bebê! 😉", "date": "6h", "likes": 35 }] },
            { "id": "c4-8", "user": { "name": "Ricardo", "avatarUrl": "https://randomuser.me/api/portraits/men/12.jpg" }, "text": "Deusa!", "date": "6h", "likes": 70, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Sou mesmo! 😇", "date": "6h", "likes": 33 }] },
            { "id": "c4-9", "user": { "name": "André", "avatarUrl": "https://randomuser.me/api/portraits/men/13.jpg" }, "text": "Que energia boa!", "date": "5h", "likes": 68, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "A minha energia contagia, né? 😉", "date": "5h", "likes": 31 }] },
            { "id": "c4-10", "user": { "name": "Felipe", "avatarUrl": "https://randomuser.me/api/portraits/men/14.jpg" }, "text": "Deixou com vontade e saiu correndo...", "date": "5h", "likes": 65, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Jamais! Só tô esperando você pra gente continuar... 😉", "date": "4h", "likes": 30 }] },
            { "id": "c4-11", "user": { "name": "Rafael", "avatarUrl": "https://randomuser.me/api/portraits/men/15.jpg" }, "text": "Manda um beijo pra mim?", "date": "4h", "likes": 62, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Claro, meu amor! Um beijo bem gostoso! 💋", "date": "4h", "likes": 28 }] },
            { "id": "c4-12", "user": { "name": "Daniel", "avatarUrl": "https://randomuser.me/api/portraits/men/16.jpg" }, "text": "Que espetáculo de mulher!", "date": "4h", "likes": 59, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Sou um espetáculo que vale a pena ver de perto. 😏", "date": "4h", "likes": 27 }] },
            { "id": "c4-13", "user": { "name": "Gustavo", "avatarUrl": "https://randomuser.me/api/portraits/men/17.jpg" }, "text": "Me deixa louco", "date": "4h", "likes": 57, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "E eu adoro isso! 😉", "date": "4h", "likes": 26 }] },
            { "id": "c4-14", "user": { "name": "Marcelo", "avatarUrl": "https://randomuser.me/api/portraits/men/18.jpg" }, "text": "Não tenho estruturas", "date": "3h", "likes": 54, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "É pra perder as estruturas mesmo, meu bem!", "date": "3h", "likes": 25 }] },
            { "id": "c4-15", "user": { "name": "Rodrigo", "avatarUrl": "https://randomuser.me/api/portraits/men/19.jpg" }, "text": "Que provocação...", "date": "3h", "likes": 52, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "Sou especialista em provocar...", "date": "3h", "likes": 23 }] },
            { "id": "c4-16", "user": { "name": "Diego", "avatarUrl": "https://randomuser.me/api/portraits/men/20.jpg" }, "text": "Com essa legenda, já sei que a noite vai ser boa.", "date": "3h", "likes": 49, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "A noite pode ser mais do que boa. Pode ser inesquecível.", "date": "3h", "likes": 21 }] },
            { "id": "c4-17", "user": { "name": "Thiago", "avatarUrl": "https://randomuser.me/api/portraits/men/21.jpg" }, "text": "Isso devia ser proibido", "date": "2h", "likes": 47, "replies": [{ "user": { "name": "Yasmin", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/4a67e130ab33672528eba4ce4e0df5ec.jpg" }, "text": "O que é proibido é mais gostoso, não acha?", "date": "2h", "likes": 20 }] }
        ]
    },
    {
        "id": "video-5",
        "user": {
            "name": "Sara",
            "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg"
        },
        "imageUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg",
        "videoUrl": "https://madames.online/wp-content/uploads/2025/10/Big-Tits-Huge-Tits-Natural-Tits-TikTok-Tits-Porn-GIF-by-leahgoes.mp4",
        "caption": "Sei exatamente como te deixar viciado em mim... 😈",
        "likes": 1216,
        "comments": [
            { "id": "c5-1", "user": { "name": "Rafael", "avatarUrl": "https://randomuser.me/api/portraits/men/37.jpg" }, "text": "Então me vicia, tô esperando.", "date": "9h", "likes": 102, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Te mostro como te viciar... 🔥", "date": "8h", "likes": 52 }] },
            { "id": "c5-2", "user": { "name": "Carlos", "avatarUrl": "https://randomuser.me/api/portraits/men/38.jpg" }, "text": "A mais gata de todas", "date": "9h", "likes": 98, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Exagerado! Mas obrigada, lindo! ❤️", "date": "9h", "likes": 50 }] },
            { "id": "c5-3", "user": { "name": "João", "avatarUrl": "https://randomuser.me/api/portraits/men/39.jpg" }, "text": "Que energia boa!", "date": "8h", "likes": 95, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "A minha energia contagia, né? 😉", "date": "8h", "likes": 48 }] },
            { "id": "c5-4", "user": { "name": "Pedro", "avatarUrl": "https://randomuser.me/api/portraits/men/40.jpg" }, "text": "Já tô viciado só com essa legenda.", "date": "8h", "likes": 91, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Isso porque você não viu nada ainda... 😏", "date": "7h", "likes": 46 }] },
            { "id": "c5-5", "user": { "name": "Lucas", "avatarUrl": "https://randomuser.me/api/portraits/men/41.jpg" }, "text": "Me nota!", "date": "7h", "likes": 88, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Notado, meu bem! 😘", "date": "7h", "likes": 44 }] },
            { "id": "c5-6", "user": { "name": "Marcos", "avatarUrl": "https://randomuser.me/api/portraits/men/42.jpg" }, "text": "Você alegrou minha noite", "date": "7h", "likes": 85, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Fico feliz em saber, amor!", "date": "7h", "likes": 42 }] },
            { "id": "c5-7", "user": { "name": "Fernando", "avatarUrl": "https://randomuser.me/api/portraits/men/43.jpg" }, "text": "Que gata 🔥", "date": "6h", "likes": 82, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Obrigada, delícia!", "date": "6h", "likes": 40 }] },
            { "id": "c5-8", "user": { "name": "Ricardo", "avatarUrl": "https://randomuser.me/api/portraits/men/44.jpg" }, "text": "Show!", "date": "5h", "likes": 79, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Show mesmo é o que eu faço nas minhas lives... você devia ver. 😉", "date": "5h", "likes": 38 }] },
            { "id": "c5-9", "user": { "name": "André", "avatarUrl": "https://randomuser.me/api/portraits/men/45.jpg" }, "text": "Com certeza sabe como viciar...", "date": "5h", "likes": 76, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Sei de coisas que você nem imagina, meu bem. 😘", "date": "4h", "likes": 37 }] },
            { "id": "c5-10", "user": { "name": "Felipe", "avatarUrl": "https://randomuser.me/api/portraits/men/46.jpg" }, "text": "Essa mulher é um monumento", "date": "4h", "likes": 73, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "E você ainda não viu nada...", "date": "4h", "likes": 35 }] },
            { "id": "c5-11", "user": { "name": "Bruno", "avatarUrl": "https://randomuser.me/api/portraits/men/47.jpg" }, "text": "Sem condições pra tanta beleza", "date": "4h", "likes": 70, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Você teria condições de ver muito mais. 😏", "date": "4h", "likes": 33 }] },
            { "id": "c5-12", "user": { "name": "Daniel", "avatarUrl": "https://randomuser.me/api/portraits/men/48.jpg" }, "text": "Toda natural, bonita pra caramba", "date": "4h", "likes": 67, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Obrigada, amor!", "date": "4h", "likes": 31 }] },
            { "id": "c5-13", "user": { "name": "Gustavo", "avatarUrl": "https://randomuser.me/api/portraits/men/49.jpg" }, "text": "Fico hipnotizado com você", "date": "3h", "likes": 64, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "É só o começo, meu bem.", "date": "3h", "likes": 29 }] },
            { "id": "c5-14", "user": { "name": "Marcelo", "avatarUrl": "https://randomuser.me/api/portraits/men/50.jpg" }, "text": "Que dança!", "date": "3h", "likes": 61, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Gostou do meu gingado?", "date": "3h", "likes": 27 }] },
            { "id": "c5-15", "user": { "name": "Rodrigo", "avatarUrl": "https://randomuser.me/api/portraits/men/51.jpg" }, "text": "Me chama pra dançar com você", "date": "3h", "likes": 58, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Vem! A dança de verdade acontece no privado. 😉", "date": "3h", "likes": 25 }] },
            { "id": "c5-16", "user": { "name": "Diego", "avatarUrl": "https://randomuser.me/api/portraits/men/52.jpg" }, "text": "Que mulher!", "date": "2h", "likes": 55, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Sou mesmo! haha", "date": "2h", "likes": 24 }] },
            { "id": "c5-17", "user": { "name": "Thiago", "avatarUrl": "https://randomuser.me/api/portraits/men/53.jpg" }, "text": "Você é demais", "date": "2h", "likes": 52, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Você que é, fofo!", "date": "2h", "likes": 23 }] },
            { "id": "c5-18", "user": { "name": "Vinicius", "avatarUrl": "https://randomuser.me/api/portraits/men/54.jpg" }, "text": "Duvido que saiba como me viciar.", "date": "2h", "likes": 49, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Duvida? Me chama no privado que eu te mostro. 😉", "date": "1h", "likes": 22 }] },
            { "id": "c5-19", "user": { "name": "Alexandre", "avatarUrl": "https://randomuser.me/api/portraits/men/55.jpg" }, "text": "A melhor dançarina", "date": "2h", "likes": 46, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Obrigada, meu bem! Tento o meu melhor.", "date": "2h", "likes": 21 }] },
            { "id": "c5-20", "user": { "name": "Leandro", "avatarUrl": "https://randomuser.me/api/portraits/men/56.jpg" }, "text": "Que movimento!", "date": "1h", "likes": 43, "replies": [{ "user": { "name": "Sara", "avatarUrl": "https://madames.online/wp-content/uploads/2025/11/6e7441b4ddec1906ba41fa199e46cb3a.jpg" }, "text": "Gostou? Imagina ao vivo... 😏", "date": "1h", "likes": 20 }] }
        ]
    },
    {
        "id": "video-10",
        "user": {
            "name": "Debora",
            "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg"
        },
        "imageUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg",
        "videoUrl": "https://madames.online/wp-content/uploads/2026/02/Big-Tits-Bimbo-Boobs-Fake-Boobs-Lingerie-MILF-OnlyFans-Reveal-Tits-Porn-Gif-by-donatella2045-_-RedGIFs.mp4",
        "caption": "Sextou... e eu tô como? Pronta pra causar. Quem vem? 😉",
        "likes": 967,
        "comments": [
            { "id": "c10-1", "user": { "name": "Júlio", "avatarUrl": "https://randomuser.me/api/portraits/men/29.jpg" }, "text": "Eu vou! Onde é o after?", "date": "4h", "likes": 68, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "O after é na minha cama, bebê. 😉", "date": "4h", "likes": 41 }] },
            { "id": "c10-2", "user": { "name": "Antônio", "avatarUrl": "https://randomuser.me/api/portraits/men/30.jpg" }, "text": "Uma deusa pronta pro final de semana.", "date": "4h", "likes": 65, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Prontíssima! E você, tá pronto pra mim?", "date": "3h", "likes": 39 }] },
            { "id": "c10-3", "user": { "name": "Leonardo", "avatarUrl": "https://randomuser.me/api/portraits/men/31.jpg" }, "text": "Que mulherão!", "date": "3h", "likes": 62, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Com muito orgulho! hehe", "date": "3h", "likes": 37 }] },
            { "id": "c10-4", "user": { "name": "Francisco", "avatarUrl": "https://randomuser.me/api/portraits/men/32.jpg" }, "text": "Eu vou com certeza! Me chama!", "date": "3h", "likes": 59, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Só se for agora! Adoro companhia.", "date": "2h", "likes": 35 }] },
            { "id": "c10-5", "user": { "name": "Jonas", "avatarUrl": "https://randomuser.me/api/portraits/men/33.jpg" }, "text": "Debora, vc não tem defeitos.", "date": "2h", "likes": 56, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Assim você me deixa sem graça, fofo!", "date": "2h", "likes": 33 }] },
            { "id": "c10-6", "user": { "name": "Paulo", "avatarUrl": "https://randomuser.me/api/portraits/men/34.jpg" }, "text": "Se eu for, a gente vai causar muito.", "date": "2h", "likes": 53, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "É exatamente essa a intenção! 😈", "date": "2h", "likes": 31 }] },
            { "id": "c10-7", "user": { "name": "Cláudio", "avatarUrl": "https://randomuser.me/api/portraits/men/35.jpg" }, "text": "Que corpo é esse, mulher?", "date": "1h", "likes": 51, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Gostou? Imagina ao vivo.", "date": "1h", "likes": 29 }] },
            { "id": "c10-8", "user": { "name": "Maurício", "avatarUrl": "https://randomuser.me/api/portraits/men/36.jpg" }, "text": "Espetáculo de mulher!", "date": "1h", "likes": 49, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Obrigada, lindo! ❤️", "date": "1h", "likes": 28 }] },
            { "id": "c10-9", "user": { "name": "Gilberto", "avatarUrl": "https://randomuser.me/api/portraits/men/37.jpg" }, "text": "Casa comigo?", "date": "50m", "likes": 47, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Hahaha, vamos com calma, bebê!", "date": "48m", "likes": 27 }] },
            { "id": "c10-10", "user": { "name": "Valter", "avatarUrl": "https://randomuser.me/api/portraits/men/38.jpg" }, "text": "Sextou com a melhor de todas!", "date": "45m", "likes": 44, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Sextou daquele jeito! 🔥", "date": "43m", "likes": 26 }] },
            { "id": "c10-11", "user": { "name": "Sandro", "avatarUrl": "https://randomuser.me/api/portraits/men/39.jpg" }, "text": "Perfeita!", "date": "40m", "likes": 41, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Sou mesmo! 😇", "date": "38m", "likes": 24 }] },
            { "id": "c10-12", "user": { "name": "Igor", "avatarUrl": "https://randomuser.me/api/portraits/men/40.jpg" }, "text": "Você é incrível!", "date": "35m", "likes": 39, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Você que é, meu bem!", "date": "33m", "likes": 23 }] },
            { "id": "c10-13", "user": { "name": "Nelson", "avatarUrl": "https://randomuser.me/api/portraits/men/41.jpg" }, "text": "Me chama de sexta-feira e vem!", "date": "30m", "likes": 37, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Adorei! Vem mesmo! 😏", "date": "28m", "likes": 21 }] },
            { "id": "c10-14", "user": { "name": "Heitor", "avatarUrl": "https://randomuser.me/api/portraits/men/42.jpg" }, "text": "Toda produzida, amo!", "date": "25m", "likes": 35, "replies": [{ "user": { "name": "Debora", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/Happy-Sundayyyy-✨Do-you-like-my-photos-😏.jpg" }, "text": "Gosto de estar impecável pra vocês.", "date": "23m", "likes": 20 }] }
        ]
    },
    {
        "id": "video-7",
        "user": {
            "name": "Sophie",
            "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg"
        },
        "imageUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg",
        "videoUrl": "https://madames.online/wp-content/uploads/2026/02/19honeysuckle-24_7-Big-Clit-Big-Tits-Pussy-See-Through-Clothing-TikTok-hands-milfnhoney-r_sph-Porn-Gif-by-foxyysophie-_-RedGIFs.mp4",
        "caption": "Um close pra você ver os detalhes... vale o zoom? 👀",
        "likes": 895,
        "comments": [
            { "id": "c7-1", "user": { "name": "Roberto", "avatarUrl": "https://randomuser.me/api/portraits/men/23.jpg" }, "text": "Vale cada pixel de zoom! Que mulher!", "date": "5h", "likes": 67, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Adoro homens detalhistas... 😉", "date": "5h", "likes": 42 }] },
            { "id": "c7-2", "user": { "name": "Fábio", "avatarUrl": "https://randomuser.me/api/portraits/men/24.jpg" }, "text": "Você não tem defeitos, impressionante.", "date": "5h", "likes": 64, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Obrigada, amor! São seus olhos.", "date": "4h", "likes": 39 }] },
            { "id": "c7-3", "user": { "name": "Márcio", "avatarUrl": "https://randomuser.me/api/portraits/men/25.jpg" }, "text": "Dei zoom e não me arrependo.", "date": "4h", "likes": 61, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Gostou do que viu? Tem muito mais...", "date": "4h", "likes": 37 }] },
            { "id": "c7-4", "user": { "name": "Rogério", "avatarUrl": "https://randomuser.me/api/portraits/men/26.jpg" }, "text": "Que close, hein? Maravilhosa.", "date": "4h", "likes": 58, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Um close especial pra você, meu bem.", "date": "3h", "likes": 35 }] },
            { "id": "c7-5", "user": { "name": "Sérgio", "avatarUrl": "https://randomuser.me/api/portraits/men/27.jpg" }, "text": "A legenda foi um convite, né?", "date": "3h", "likes": 55, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Um convite irrecusável. 😏", "date": "3h", "likes": 33 }] },
            { "id": "c7-6", "user": { "name": "Renato", "avatarUrl": "https://randomuser.me/api/portraits/men/28.jpg" }, "text": "Que olhar poderoso!", "date": "3h", "likes": 52, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Uso ele pra conseguir tudo que eu quero.", "date": "2h", "likes": 31 }] },
            { "id": "c7-7", "user": { "name": "Júlio", "avatarUrl": "https://randomuser.me/api/portraits/men/29.jpg" }, "text": "Essa mulher é um obra de arte.", "date": "2h", "likes": 49, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "E você pode ser o apreciador... 🔥", "date": "2h", "likes": 29 }] },
            { "id": "c7-8", "user": { "name": "Antônio", "avatarUrl": "https://randomuser.me/api/portraits/men/30.jpg" }, "text": "Dei zoom e achei o paraíso.", "date": "2h", "likes": 46, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Achou? Que bom que gostou da vista.", "date": "1h", "likes": 27 }] },
            { "id": "c7-9", "user": { "name": "Leonardo", "avatarUrl": "https://randomuser.me/api/portraits/men/31.jpg" }, "text": "Cada detalhe seu é perfeito.", "date": "1h", "likes": 43, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Obrigada, fofo! Gosto de quem repara.", "date": "1h", "likes": 25 }] },
            { "id": "c7-10", "user": { "name": "Francisco", "avatarUrl": "https://randomuser.me/api/portraits/men/32.jpg" }, "text": "Que mulherão!", "date": "50m", "likes": 41, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Pode ter certeza! hehe", "date": "48m", "likes": 24 }] },
            { "id": "c7-11", "user": { "name": "Jonas", "avatarUrl": "https://randomuser.me/api/portraits/men/33.jpg" }, "text": "Valeu o zoom e a curtida.", "date": "45m", "likes": 38, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Valeu mais ainda seu comentário, lindo.", "date": "43m", "likes": 22 }] },
            { "id": "c7-12", "user": { "name": "Paulo", "avatarUrl": "https://randomuser.me/api/portraits/men/34.jpg" }, "text": "Linda demais!", "date": "40m", "likes": 35, "replies": [{ "user": { "name": "Sophie", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/good-morning.jpg" }, "text": "Obrigada, vida! 😘", "date": "38m", "likes": 20 }] }
        ]
    },
    {
        "id": "video-8",
        "user": {
            "name": "Belle",
            "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg"
        },
        "imageUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg",
        "videoUrl": "https://madames.online/wp-content/uploads/2026/02/Big-Nipples-Boobs-MILF-Nipples-Solo-Tits-dirty-fun-r_onlypornnsfw-tattedphysique-Porn-Gif-by-officialbelleohara-_-RedGIFs.mp4",
        "caption": "Sozinha na suíte… o que você faria se me pegasse assim? 😈",
        "likes": 742,
        "comments": [
            { "id": "c8-1", "user": { "name": "Márcio", "avatarUrl": "https://randomuser.me/api/portraits/men/25.jpg" }, "text": "Eu te prenderia aí dentro e só sairíamos amanhã.", "date": "3h", "likes": 69, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Adoro a ideia! Tô esperando... 😏", "date": "3h", "likes": 40 }] },
            { "id": "c8-2", "user": { "name": "Rogério", "avatarUrl": "https://randomuser.me/api/portraits/men/26.jpg" }, "text": "Faria um estrago. Com todo respeito.", "date": "3h", "likes": 66, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Sem respeito é mais gostoso. 😈", "date": "2h", "likes": 38 }] },
            { "id": "c8-3", "user": { "name": "Sérgio", "avatarUrl": "https://randomuser.me/api/portraits/men/27.jpg" }, "text": "Faria coisas que você nem imagina.", "date": "2h", "likes": 64, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Me conta, adoro imaginação fértil.", "date": "2h", "likes": 37 }] },
            { "id": "c8-4", "user": { "name": "Renato", "avatarUrl": "https://randomuser.me/api/portraits/men/28.jpg" }, "text": "Que suíte, hein? Mas você é a melhor parte.", "date": "2h", "likes": 62, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Sou a atração principal, né? hehe", "date": "2h", "likes": 35 }] },
            { "id": "c8-5", "user": { "name": "Júlio", "avatarUrl": "https://randomuser.me/api/portraits/men/29.jpg" }, "text": "Se eu te pego assim, o hotel vem abaixo.", "date": "2h", "likes": 60, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Gosto de barulho... pode vir.", "date": "1h", "likes": 33 }] },
            { "id": "c8-6", "user": { "name": "Antônio", "avatarUrl": "https://randomuser.me/api/portraits/men/30.jpg" }, "text": "Você é um perigo, mulher.", "date": "1h", "likes": 58, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "O perigo mais gostoso que você vai encontrar.", "date": "1h", "likes": 32 }] },
            { "id": "c8-7", "user": { "name": "Leonardo", "avatarUrl": "https://randomuser.me/api/portraits/men/31.jpg" }, "text": "A pergunta é: o que VOCÊ faria?", "date": "1h", "likes": 56, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Eu te mostraria o que é prazer de verdade. 😉", "date": "1h", "likes": 30 }] },
            { "id": "c8-8", "user": { "name": "Francisco", "avatarUrl": "https://randomuser.me/api/portraits/men/32.jpg" }, "text": "Gata demais!", "date": "1h", "likes": 53, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Obrigada, lindo! ❤️", "date": "55m", "likes": 29 }] },
            { "id": "c8-9", "user": { "name": "Jonas", "avatarUrl": "https://randomuser.me/api/portraits/men/33.jpg" }, "text": "Eu te faria esquecer seu nome.", "date": "50m", "likes": 51, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Desafio aceito. Vem tentar.", "date": "48m", "likes": 28 }] },
            { "id": "c8-10", "user": { "name": "Paulo", "avatarUrl": "https://randomuser.me/api/portraits/men/34.jpg" }, "text": "Espetacular!", "date": "45m", "likes": 49, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Você não viu nada ainda.", "date": "43m", "likes": 27 }] },
            { "id": "c8-11", "user": { "name": "Cláudio", "avatarUrl": "https://randomuser.me/api/portraits/men/35.jpg" }, "text": "Não tenho estruturas pra você.", "date": "40m", "likes": 47, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "É pra perder as estruturas mesmo.", "date": "38m", "likes": 26 }] },
            { "id": "c8-12", "user": { "name": "Maurício", "avatarUrl": "https://randomuser.me/api/portraits/men/36.jpg" }, "text": "Primeiro eu te amarrava...", "date": "35m", "likes": 45, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Opa, gostei de como você pensa. Continue...", "date": "33m", "likes": 25 }] },
            { "id": "c8-13", "user": { "name": "Gilberto", "avatarUrl": "https://randomuser.me/api/portraits/men/37.jpg" }, "text": "Sonho de consumo.", "date": "30m", "likes": 42, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Posso ser seu sonho realizado.", "date": "28m", "likes": 23 }] },
            { "id": "c8-14", "user": { "name": "Valter", "avatarUrl": "https://randomuser.me/api/portraits/men/38.jpg" }, "text": "Com certeza não te deixaria sozinha.", "date": "25m", "likes": 40, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Ainda bem, detesto ficar sozinha.", "date": "23m", "likes": 22 }] },
            { "id": "c8-15", "user": { "name": "Sandro", "avatarUrl": "https://randomuser.me/api/portraits/men/39.jpg" }, "text": "Uau! Que mulher!", "date": "20m", "likes": 38, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Gostou, foi? 😏", "date": "18m", "likes": 21 }] },
            { "id": "c8-16", "user": { "name": "Igor", "avatarUrl": "https://randomuser.me/api/portraits/men/40.jpg" }, "text": "Perdi o ar aqui.", "date": "15m", "likes": 36, "replies": [{ "user": { "name": "Belle", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/The-Santa-Barbara-sunset-is-beautiful-Everyone-kept-starring-at-me-though.-I-think-the-last-sl.jpg" }, "text": "Recupera e vem correndo.", "date": "13m", "likes": 20 }] }
        ]
    },
    {
        "id": "video-9",
        "user": {
            "name": "Rita",
            "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg"
        },
        "imageUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg",
        "videoUrl": "https://madames.online/wp-content/uploads/2026/02/Amateur-OnlyFans-Pussy-Porn-Gif-by-ritaa-_-RedGIFs.mp4",
        "caption": "Já fiz minha parte… o resto é com você. 💦 #suavez",
        "likes": 829,
        "comments": [
            { "id": "c9-1", "user": { "name": "Sérgio", "avatarUrl": "https://randomuser.me/api/portraits/men/27.jpg" }, "text": "Me manda o endereço que eu chego em 5 minutos!", "date": "4h", "likes": 66, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Tô no seu pensamento, amor. Chega rapidinho. 😉", "date": "4h", "likes": 40 }] },
            { "id": "c9-2", "user": { "name": "Renato", "avatarUrl": "https://randomuser.me/api/portraits/men/28.jpg" }, "text": "Meu Deus, que mulher.", "date": "4h", "likes": 63, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Em carne, osso e muita vontade.", "date": "3h", "likes": 38 }] },
            { "id": "c9-3", "user": { "name": "Júlio", "avatarUrl": "https://randomuser.me/api/portraits/men/29.jpg" }, "text": "Pode deixar que eu termino o serviço.", "date": "3h", "likes": 61, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Tô contando com isso... não me decepciona.", "date": "3h", "likes": 37 }] },
            { "id": "c9-4", "user": { "name": "Antônio", "avatarUrl": "https://randomuser.me/api/portraits/men/30.jpg" }, "text": "Que corpo!", "date": "3h", "likes": 59, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Feito pra te enlouquecer.", "date": "3h", "likes": 35 }] },
            { "id": "c9-5", "user": { "name": "Leonardo", "avatarUrl": "https://randomuser.me/api/portraits/men/31.jpg" }, "text": "Sua vez, né? Tô pronto!", "date": "3h", "likes": 57, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Gosto de homens prontos. Vem!", "date": "2h", "likes": 33 }] },
            { "id": "c9-6", "user": { "name": "Francisco", "avatarUrl": "https://randomuser.me/api/portraits/men/32.jpg" }, "text": "Deliciosa!", "date": "2h", "likes": 54, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Você nem imagina o quanto.", "date": "2h", "likes": 31 }] },
            { "id": "c9-7", "user": { "name": "Jonas", "avatarUrl": "https://randomuser.me/api/portraits/men/33.jpg" }, "text": "O resto deixa comigo, relaxa.", "date": "2h", "likes": 52, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Adoro quando tomam a iniciativa. 🔥", "date": "2h", "likes": 30 }] },
            { "id": "c9-8", "user": { "name": "Paulo", "avatarUrl": "https://randomuser.me/api/portraits/men/34.jpg" }, "text": "Mulher perfeita existe e eu posso provar.", "date": "2h", "likes": 50, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "A prova tá aqui, esperando.", "date": "1h", "likes": 28 }] },
            { "id": "c9-9", "user": { "name": "Cláudio", "avatarUrl": "https://randomuser.me/api/portraits/men/35.jpg" }, "text": "Deixa comigo que eu sei o que fazer.", "date": "1h", "likes": 48, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Então me mostra, bebê.", "date": "1h", "likes": 27 }] },
            { "id": "c9-10", "user": { "name": "Maurício", "avatarUrl": "https://randomuser.me/api/portraits/men/36.jpg" }, "text": "Que espetáculo!", "date": "1h", "likes": 46, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "O show só começou.", "date": "1h", "likes": 26 }] },
            { "id": "c9-11", "user": { "name": "Gilberto", "avatarUrl": "https://randomuser.me/api/portraits/men/37.jpg" }, "text": "Minha vez de te fazer suar.", "date": "1h", "likes": 43, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Amo um desafio. Vem com tudo.", "date": "1h", "likes": 24 }] },
            { "id": "c9-12", "user": { "name": "Valter", "avatarUrl": "https://randomuser.me/api/portraits/men/38.jpg" }, "text": "Que tentação.", "date": "50m", "likes": 41, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Cai em tentação, vale a pena.", "date": "49m", "likes": 23 }] },
            { "id": "c9-13", "user": { "name": "Sandro", "avatarUrl": "https://randomuser.me/api/portraits/men/39.jpg" }, "text": "Assim você me mata.", "date": "48m", "likes": 39, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Mato de prazer, né?", "date": "47m", "likes": 22 }] },
            { "id": "c9-14", "user": { "name": "Igor", "avatarUrl": "https://randomuser.me/api/portraits/men/40.jpg" }, "text": "Já tô a caminho pra fazer minha parte.", "date": "46m", "likes": 37, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Tô te esperando ansiosa.", "date": "45m", "likes": 21 }] },
            { "id": "c9-15", "user": { "name": "Nelson", "avatarUrl": "https://randomuser.me/api/portraits/men/41.jpg" }, "text": "Musa!", "date": "44m", "likes": 35, "replies": [{ "user": { "name": "Rita", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/BewitchedSparklingXenoposeidon-mobile.jpg" }, "text": "Pode me chamar assim, eu deixo.", "date": "43m", "likes": 20 }] }
        ]
    },
    {
        "id": "video-6",
        "user": {
            "name": "Natalia",
            "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg"
        },
        "imageUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg",
        "videoUrl": "https://madames.online/wp-content/uploads/2026/02/Hotwife-Housewife-MILF-Redhead-Wife-Wifey-Porn-Gif-by-goddessnatalia-_-RedGIFs.mp4",
        "caption": "Imagina eu me exibindo assim na sua frente... 🤫 #soadmira",
        "likes": 911,
        "comments": [
            { "id": "c6-1", "user": { "name": "Jorge", "avatarUrl": "https://randomuser.me/api/portraits/men/21.jpg" }, "text": "Ficaria só admirando mesmo, uma obra de arte.", "date": "4h", "likes": 64, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Admirar é bom, mas tocar é melhor ainda. 😉", "date": "4h", "likes": 39 }] },
            { "id": "c6-2", "user": { "name": "Eduardo", "avatarUrl": "https://randomuser.me/api/portraits/men/22.jpg" }, "text": "Essa cor realçou ainda mais sua beleza.", "date": "4h", "likes": 61, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Que bom que você gostou, meu bem! ❤️", "date": "3h", "likes": 37 }] },
            { "id": "c6-3", "user": { "name": "Roberto", "avatarUrl": "https://randomuser.me/api/portraits/men/23.jpg" }, "text": "Difícil só admirar, hein?", "date": "3h", "likes": 59, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "E quem disse que é pra só admirar? 😏", "date": "3h", "likes": 36 }] },
            { "id": "c6-4", "user": { "name": "Fábio", "avatarUrl": "https://randomuser.me/api/portraits/men/24.jpg" }, "text": "Que ruiva espetacular!", "date": "3h", "likes": 57, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "O fogo acompanha a cor do cabelo. 🔥", "date": "2h", "likes": 34 }] },
            { "id": "c6-5", "user": { "name": "Márcio", "avatarUrl": "https://randomuser.me/api/portraits/men/25.jpg" }, "text": "Eu não ia aguentar ficar só olhando.", "date": "2h", "likes": 55, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "E quem disse que eu quero que você só olhe?", "date": "2h", "likes": 32 }] },
            { "id": "c6-6", "user": { "name": "Rogério", "avatarUrl": "https://randomuser.me/api/portraits/men/26.jpg" }, "text": "Gata demais!", "date": "2h", "likes": 52, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Obrigada, lindo! ❤️", "date": "1h", "likes": 31 }] },
            { "id": "c6-7", "user": { "name": "Sérgio", "avatarUrl": "https://randomuser.me/api/portraits/men/27.jpg" }, "text": "A mulher mais linda que eu já vi.", "date": "1h", "likes": 50, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Assim você me deixa sem jeito.", "date": "1h", "likes": 30 }] },
            { "id": "c6-8", "user": { "name": "Renato", "avatarUrl": "https://randomuser.me/api/portraits/men/28.jpg" }, "text": "Admirar? Eu ia pular em cima.", "date": "1h", "likes": 48, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Gosto de atitude! Vem.", "date": "1h", "likes": 28 }] },
            { "id": "c6-9", "user": { "name": "Júlio", "avatarUrl": "https://randomuser.me/api/portraits/men/29.jpg" }, "text": "Casa comigo?", "date": "50m", "likes": 46, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Hahaha, um passo de cada vez, fofo.", "date": "49m", "likes": 26 }] },
            { "id": "c6-10", "user": { "name": "Antônio", "avatarUrl": "https://randomuser.me/api/portraits/men/30.jpg" }, "text": "Você é um sonho.", "date": "48m", "likes": 43, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Um sonho que pode se tornar realidade.", "date": "47m", "likes": 25 }] },
            { "id": "c6-11", "user": { "name": "Leonardo", "avatarUrl": "https://randomuser.me/api/portraits/men/31.jpg" }, "text": "Missão impossível só admirar.", "date": "46m", "likes": 41, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Missões impossíveis são as melhores.", "date": "45m", "likes": 23 }] },
            { "id": "c6-12", "user": { "name": "Francisco", "avatarUrl": "https://randomuser.me/api/portraits/men/32.jpg" }, "text": "Que corpo!", "date": "44m", "likes": 39, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Gostou? Tem mais pra ver.", "date": "43m", "likes": 22 }] },
            { "id": "c6-13", "user": { "name": "Jonas", "avatarUrl": "https://randomuser.me/api/portraits/men/33.jpg" }, "text": "Perfeita!", "date": "42m", "likes": 37, "replies": [{ "user": { "name": "Natalia", "avatarUrl": "https://madames.online/wp-content/uploads/2026/02/👠😘.jpg" }, "text": "Chega perto e descobre.", "date": "41m", "likes": 21 }] }
        ]
    }
];
